/**
 * fpack subtractive-dither dequantization support.
 *
 * When astropy/CFITSIO quantizes floats with `SUBTRACTIVE_DITHER_1/2`, a
 * per-pixel dither offset drawn from a seeded pseudo-random sequence is added
 * before rounding to int32. To recover the float we must subtract the same
 * offset back: `float = (int - dither + 0.5) * ZSCALE + ZZERO`. The dither
 * sequence and its per-tile starting point are fully determined by the file
 * (the `ZDITHER0` seed and the tile's row index), so decode is deterministic.
 *
 * This mirrors CFITSIO's `unquantize_*` (vendored in astropy as
 * `hdu/compressed/src/unquantize.c`) and its `fits_init_randoms` table exactly:
 *
 *   - The 10000-entry random table is generated by a Park–Miller minimal-
 *     standard generator (a=16807, m=2^31-1, seed=1) and stored as **float32**.
 *   - Per tile: `iseed = (tileIndex + ZDITHER0 - 1) mod 10000`, then
 *     `nextrand = trunc(rand[iseed] * 500)`; `nextrand` advances once per pixel
 *     (including blank/zero pixels) and re-seeds from the table on wrap.
 *   - `SUBTRACTIVE_DITHER_2` additionally stores exact-zero pixels via the
 *     sentinel value −2147483646, decoded back to exactly 0.0 (no dither).
 */

export const NO_DITHER = -1;
export const SUBTRACTIVE_DITHER_1 = 1;
export const SUBTRACTIVE_DITHER_2 = 2;

/** Size of the CFITSIO random-number table (`N_RANDOM`). Do not change. */
export const N_RANDOM = 10000;

/** Sentinel integer for an exact-0.0 pixel under `SUBTRACTIVE_DITHER_2`. */
export const DITHER_ZERO_VALUE = -2147483646;

/** Map a `ZQUANTIZ` keyword to a dither-method code (absent / unknown → NO_DITHER). */
export function ditherMethodFromZquantiz(zquantiz: string | undefined): number {
  switch (zquantiz) {
    case 'SUBTRACTIVE_DITHER_1':
      return SUBTRACTIVE_DITHER_1;
    case 'SUBTRACTIVE_DITHER_2':
      return SUBTRACTIVE_DITHER_2;
    default:
      // 'NO_DITHER', 'NONE', or no keyword at all: no dither to reverse.
      return NO_DITHER;
  }
}

let randomTable: Float32Array | null = null;

/**
 * The CFITSIO random-number table, generated lazily and cached. Values are
 * stored as float32 to match CFITSIO's `(float)(seed/m)` store bit-for-bit.
 */
export function ditherRandomTable(): Float32Array {
  if (randomTable !== null) return randomTable;
  const table = new Float32Array(N_RANDOM);
  const a = 16807.0;
  const m = 2147483647.0;
  let seed = 1.0;
  for (let i = 0; i < N_RANDOM; i++) {
    const temp = a * seed;
    // temp/m is non-negative, so Math.trunc matches C's `(int)` truncation.
    seed = temp - m * Math.trunc(temp / m);
    table[i] = seed / m; // assignment to Float32Array rounds to float32
  }
  // CFITSIO invariant: after the loop the seed must be exactly 1043618065. If it
  // is not, the sequence diverged and every dithered tile would decode wrong.
  if (Math.trunc(seed) !== 1043618065) {
    throw new Error(
      `dither: random-table generation diverged from the CFITSIO sequence ` +
        `(final seed ${seed}, expected 1043618065)`,
    );
  }
  randomTable = table;
  return table;
}
